### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by Abel1802** [KAIST-MACLab/PyTSMod#15]
**Describe the bug**
TypeError: slice indices must be integers or None or have an __index__ method

This error occered when I was runing the code of tutorial.
<img width="1081" alt="TypeError" src="https://user-images.githubusercontent.com/55339089/99865855-95775e80-2be7-11eb-9d1f-38190a240642.png">

**Comment by seyong92** [comment]
Hi, could you tell me your NumPy version and the shape of your audio signal?

Maybe it can be a version issue of NumPy.

**Comment by Abel1802** [comment]
Thank you for your reply.
I used two audio signals which are wav1 and wav2. But they all encountered the same problem.
<img width="255" alt="Screen Shot 2020-11-24 at 9 35 08 AM" src="https://user-images.githubusercontent.com/55339089/100035109-6572ca00-2e38-11eb-993c-65d31327b9bb.png">

**Comment by seyong92** [comment]
Hi, I just found that the issue is from the NumPy dtype of old versions.

If there is no reason to use the specific version of NumPy, I would recommend you to use the latest one.

Otherwise, just wait for the bug fixed version. I will update it ASAP.

**Comment by seyong92** [comment]
The version 0.3.3 just came out! The issue is solved. Thank you for your report!
