### ISSUE TITLE
Getting Error while Implementing wsola for time stretching using 2 x n array of anchor points 

### ISSUE THREAD

**Issue by anupama-deo** [KAIST-MACLab/PyTSMod#21]
While implementing wsola  for time stretching using 2 x n array of anchor points got the following error:
ValueError: index can't contain negative values
It happens for only certain combination of anchor points.
 for eg if I want to change the audio length in the following ratio:[ 1, 1.1, 1.2, 0.9] i give the 2 X n array as:
np.array([[0, x_length/4, 2*x_length/4, 3*x_length/4, x_length], [0, x_length/4 * 1 ,  2*x_length/4 * 1.1,  3*x_length/4 * 1.2 ,
x_length * 0.9]]])
it gives the error :ValueError: array is too big; `arr.size * arr.dtype.itemsize` is larger than the maximum possible size. or sometimes
ValueError: index can't contain negative values.
but it works fine for the anchor list [ 1, 1.1, 1.2, 0.8] or  [1, 1.1, 1.2, 1]. Is there anything I am missing

**Comment by seyong92** [comment]
It seems that you want to change the stretching ratio for every quarter of audio.

The definition of anchor points are not the just ratio of the certain part. It is a final sample point of the output.

For example, if anchor point is np.array([[0, x_length], [0, round(x_length * 1.3)]]), it means WSOLA will change the whole audio with fixed stretching rate 1.3

If anchor point is np.array([[0, x_length // 2, x_length], [0, x_length, round(x_length * 1.5)]]), it means that the first half of the original audio will be stretched by 2, and the rest of the audio will not be changed.

So I think you should use the anchor points as np.array([[0, x_length // 4, x_length // 2, 3 * x_length // 4, x_length], [0, x_length // 4, round(x_length // 4 + (x_length // 4) * 1.1), round(x_length // 4 + (x_length // 4) * 1.1 + (x_length // 4) * 1.2), round(x_length // 4 + (x_length // 4) * 1.1 + (x_length // 4) * 1.2 + (x_length // 4) * 0.9)]])

I think this will solve your problem.

**Comment by anupama-deo** [comment]
Thanks a lot it is working now
