### ISSUE TITLE
Latest Version of PyTSMod Unavailable for Python 3.11

### ISSUE THREAD

**Issue by julbean** [KAIST-MACLab/PyTSMod#23]
PyTSMod versions 0.3.6, 0.3.5, and 0.3.4 all require Python versions 3.8, 3.9, or 3.10.  Since version 0.3.3 is less restricted, it's what gets installed when running "pip install pytsmod" on Python 3.11.  In particular, this means installing on Python 3.11 still gives librosa (and by extension numba) as a dependency, which is a bit of bloat and causes issues with things like nuitka compilation.

Great package by the way, love your work!

**Comment by seyong92** [comment]
We were aware of the issue, but when 3.11 first came out, some of our dependencies weren't working properly, so we didn't update them. Thanks for bringing this to our attention. We'll get to it soon :)

**Comment by seyong92** [comment]
@julbean I just updated the package to 0.3.7 and now it supports Python 3.11. Enjoy!

**Comment by julbean** [comment]
Same issue as before, but this time with Python 3.13
